// Converting pixel array to C++ byte array based on display Draw Modes
function resolveSettingsContract() {
    if (typeof globalThis !== "undefined" && globalThis.Image2CppSettings) {
        return globalThis.Image2CppSettings;
    }

    if (typeof module !== "undefined" && module.exports && typeof require === "function") {
        try {
            return require("./core/settings.js");
        } catch (error) {
            return null;
        }
    }

    return null;
}

function normalizeGeneratorSettings(settings) {
    const contract = resolveSettingsContract();
    if (contract && typeof contract.normalizeSettings === "function") {
        return contract.normalizeSettings(settings || {});
    }

    const source = settings || {};

    return {
        width: Number(source.width) || 128,
        height: Number(source.height) || 64,
        scale: source.scale || "fit",
        contrast: Number.isFinite(Number(source.contrast)) ? Number(source.contrast) : 0,
        threshold: Number.isFinite(Number(source.threshold)) ? Number(source.threshold) : 128,
        processingMethod: "threshold",
        dither: false,
        invert: Boolean(source.invert),
        invertBg: source.invertBg === true,
        flipH: Boolean(source.flipH),
        flipV: Boolean(source.flipV),
        rotate: Number.isFinite(Number(source.rotate)) ? Number(source.rotate) : 0,
        outputFormat: source.outputFormat || "arduino",
        drawMode: source.drawMode || "vertical",
        varName: source.varName || "bitmap",
        theme: source.theme || "oled-white",
    };
}

function mergeFrameSettings(baseSettings, frameTuning) {
    const contract = resolveSettingsContract();
    if (contract && typeof contract.mergeFrameTuning === "function") {
        return contract.mergeFrameTuning(baseSettings, frameTuning || {});
    }

    return Object.assign({}, baseSettings, frameTuning || {});
}

const Generator = {

    generate(settings) {
        const safeSettings = normalizeGeneratorSettings(settings);

        if (Processor.sourceIsGif && Processor.gifFrames.length > 0) {
            let out = `// Generated by image2cpp\n// Frames: ${Processor.gifFrames.length}, Size: ${safeSettings.width}x${safeSettings.height} px\n\n`;
            let tempCanvas = document.createElement('canvas');
            tempCanvas.width = safeSettings.width;
            tempCanvas.height = safeSettings.height;

            let allNames = [];

            Processor.gifFrames.forEach((frame, idx) => {
                const frameSettings = mergeFrameSettings(safeSettings, frame.tuning || {});
                let frameData = Processor.processFrame(tempCanvas, frame.imgData, frameSettings);
                let suffix = `_${idx}`;
                allNames.push(`${safeSettings.varName}${suffix}`);
                out += this.generateFrameFromNormalizedSettings(frameData.binaryData, safeSettings, suffix) + "\n\n";
            });

            // Add array of pointers
            let strType = safeSettings.outputFormat === 'arduino' ? 'const unsigned char* const PROGMEM' : 'const unsigned char* const';
            out += `${strType} ${safeSettings.varName}_frames[] = {\n  `;
            out += allNames.join(", ") + "\n};\n";

            return out;
        } else {
            let tempCanvas = document.createElement('canvas');
            tempCanvas.width = safeSettings.width;
            tempCanvas.height = safeSettings.height;
            let result = Processor.processFrame(tempCanvas, Processor.sourceImage, safeSettings);

            return `// Generated by image2cpp\n// Size: ${safeSettings.width}x${safeSettings.height} px\n\n` + this.generateFrameFromNormalizedSettings(result.binaryData, safeSettings, "");
        }
    },

    generateFrame(binaryData, settings, suffix = "") {
        const safeSettings = normalizeGeneratorSettings(settings);

        return this.generateFrameFromNormalizedSettings(binaryData, safeSettings, suffix);
    },

    generateFrameFromNormalizedSettings(binaryData, safeSettings, suffix = "") {

        let name = safeSettings.varName + suffix;
        let mode = safeSettings.drawMode;
        let format = safeSettings.outputFormat;
        let width = safeSettings.width;
        let height = safeSettings.height;
        let out = "";

        if (!binaryData || typeof binaryData.length !== "number") {
            throw new Error("Generator.generateFrame requires a binaryData array-like input.");
        }

        const expectedLength = width * height;
        if (binaryData.length < expectedLength) {
            throw new Error(`Generator.generateFrame expected at least ${expectedLength} pixels, received ${binaryData.length}.`);
        }

        let bytes = [];
        if (mode === 'horizontal') {
            for (let y = 0; y < height; y++) {
                let currentByte = 0;
                let bitCount = 0;
                for (let x = 0; x < width; x++) {
                    let bit = binaryData[y * width + x];
                    currentByte = (currentByte << 1) | bit;
                    bitCount++;

                    if (bitCount === 8) {
                        bytes.push(currentByte);
                        currentByte = 0;
                        bitCount = 0;
                    }
                }
                if (bitCount > 0) {
                    currentByte = currentByte << (8 - bitCount);
                    bytes.push(currentByte);
                }
            }
        } else if (mode === 'vertical') {
            let pages = Math.ceil(height / 8);
            for (let p = 0; p < pages; p++) {
                for (let x = 0; x < width; x++) {
                    let currentByte = 0;
                    for (let bit = 0; bit < 8; bit++) {
                        let y = p * 8 + bit;
                        if (y < height) {
                            let val = binaryData[y * width + x];
                            currentByte |= (val << bit);
                        }
                    }
                    bytes.push(currentByte);
                }
            }
        }

        let strType = format === 'arduino' ? 'const unsigned char PROGMEM' : 'const unsigned char';
        out += `${strType} ${name}[] = {\n  `;

        for (let i = 0; i < bytes.length; i++) {
            let hex = "0x" + bytes[i].toString(16).padStart(2, '0').toUpperCase();
            out += hex + ", ";
            if ((i + 1) % 16 === 0 && i !== bytes.length - 1) out += "\n  ";
        }

        out += `\n};\n`;
        return out;
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = Generator;
}

if (typeof globalThis !== 'undefined') {
    globalThis.Generator = Generator;
}


