// Converting pixel array to C++ byte array based on display Draw Modes
const Generator = {

    generate(settings) {
        if (Processor.sourceIsGif && Processor.gifFrames.length > 0) {
            let out = `// Generated by image2cpp\n// Frames: ${Processor.gifFrames.length}, Size: ${settings.width}x${settings.height} px\n\n`;
            let tempCanvas = document.createElement('canvas');
            tempCanvas.width = settings.width;
            tempCanvas.height = settings.height;
            
            let allNames = [];
            
            Processor.gifFrames.forEach((frame, idx) => {
                let frameData = Processor.processFrame(tempCanvas, frame.imgData, Object.assign({}, settings, frame.tuning || {}));
                let suffix = `_${idx}`;
                allNames.push(`${settings.varName}${suffix}`);
                out += this.generateFrame(frameData.binaryData, settings, suffix) + "\n\n";
            });

            // Add array of pointers
            let strType = settings.outputFormat === 'arduino' ? 'const unsigned char* const PROGMEM' : 'const unsigned char* const';
            out += `${strType} ${settings.varName}_frames[] = {\n  `;
            out += allNames.join(", ") + "\n};\n";
            
            return out;
        } else {
            let tempCanvas = document.createElement('canvas');
            tempCanvas.width = settings.width;
            tempCanvas.height = settings.height;
            let result = Processor.processFrame(tempCanvas, Processor.sourceImage, settings);
            
            return `// Generated by image2cpp\n// Size: ${settings.width}x${settings.height} px\n\n` + this.generateFrame(result.binaryData, settings, "");
        }
    },

    generateFrame(binaryData, settings, suffix = "") {
        let name = settings.varName + suffix;
        let mode = settings.drawMode;
        let format = settings.outputFormat;
        let width = settings.width;
        let height = settings.height;
        let out = "";

        let bytes = [];
        if (mode === 'horizontal') {
            for (let y = 0; y < height; y++) {
                let currentByte = 0;
                let bitCount = 0;
                for (let x = 0; x < width; x++) {
                    let bit = binaryData[y * width + x];
                    currentByte = (currentByte << 1) | bit;
                    bitCount++;

                    if (bitCount === 8) {
                        bytes.push(currentByte);
                        currentByte = 0;
                        bitCount = 0;
                    }
                }
                if (bitCount > 0) {
                    currentByte = currentByte << (8 - bitCount);
                    bytes.push(currentByte);
                }
            }
        } else if (mode === 'vertical') {
            let pages = Math.ceil(height / 8);
            for (let p = 0; p < pages; p++) {
                for (let x = 0; x < width; x++) {
                    let currentByte = 0;
                    for (let bit = 0; bit < 8; bit++) {
                        let y = p * 8 + bit;
                        if (y < height) {
                            let val = binaryData[y * width + x];
                            currentByte |= (val << bit);
                        }
                    }
                    bytes.push(currentByte);
                }
            }
        }

        let strType = format === 'arduino' ? 'const unsigned char PROGMEM' : 'const unsigned char';
        out += `${strType} ${name}[] = {\n  `;
        
        for (let i = 0; i < bytes.length; i++) {
            let hex = "0x" + bytes[i].toString(16).padStart(2, '0').toUpperCase();
            out += hex + ", ";
            if ((i + 1) % 16 === 0 && i !== bytes.length - 1) out += "\n  ";
        }
        
        out += `\n};\n`;
        return out;
    }
};


