const assert = require("assert");
const Generator = require("../js/generator.js");

function makeBinary(width, height, points) {
    const data = new Uint8Array(width * height);
    (points || []).forEach((point) => {
        const x = point[0];
        const y = point[1];
        if (x >= 0 && x < width && y >= 0 && y < height) {
            data[y * width + x] = 1;
        }
    });
    return data;
}

const originalDocument = global.document;
const originalProcessor = global.Processor;

try {
    const processCalls = [];

    global.document = {
        createElement(tagName) {
            assert.strictEqual(tagName, "canvas");
            return { width: 0, height: 0 };
        },
    };

    const staticBinary = makeBinary(8, 8, []);
    const gifFrame0Binary = makeBinary(8, 8, []);
    const gifFrame1Binary = makeBinary(8, 8, [
        [0, 0],
        [1, 0],
        [2, 0],
        [3, 0],
        [4, 0],
        [5, 0],
        [6, 0],
        [7, 0],
    ]);

    const staticSource = { kind: "static-source" };
    const gifFrame0 = { kind: "gif-frame-0" };
    const gifFrame1 = { kind: "gif-frame-1" };

    global.Processor = {
        sourceIsGif: false,
        sourceImage: staticSource,
        gifFrames: [],
        processFrame(canvas, source, settings) {
            processCalls.push({ source, settings: Object.assign({}, settings) });

            if (source === staticSource) {
                return { binaryData: staticBinary };
            }
            if (source === gifFrame0) {
                return { binaryData: gifFrame0Binary };
            }
            if (source === gifFrame1) {
                return { binaryData: gifFrame1Binary };
            }

            throw new Error("Unexpected source in processFrame stub.");
        },
    };

    const staticSettings = {
        width: 8,
        height: 8,
        drawMode: "vertical",
        outputFormat: "plain",
        varName: "static_img",
        contrast: 0,
    };

    const staticOutput = Generator.generate(staticSettings);
    const expectedStaticOutput = [
        "// Generated by image2cpp",
        "// Size: 8x8 px",
        "",
        "const unsigned char static_img[] = {",
        "  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, ",
        "};",
        "",
    ].join("\n");

    assert.strictEqual(staticOutput, expectedStaticOutput);

    global.Processor.sourceIsGif = true;
    global.Processor.gifFrames = [
        { imgData: gifFrame0, delay: 5, tuning: { contrast: 0 } },
        { imgData: gifFrame1, delay: 5, tuning: { contrast: 77 } },
    ];

    const gifSettings = {
        width: 8,
        height: 8,
        drawMode: "vertical",
        outputFormat: "plain",
        varName: "anim",
        contrast: 0,
    };

    const gifOutput = Generator.generate(gifSettings);
    const expectedGifOutput = [
        "// Generated by image2cpp",
        "// Frames: 2, Size: 8x8 px",
        "",
        "const unsigned char anim_0[] = {",
        "  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, ",
        "};",
        "",
        "",
        "const unsigned char anim_1[] = {",
        "  0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, ",
        "};",
        "",
        "",
        "const unsigned char* const anim_frames[] = {",
        "  anim_0, anim_1",
        "};",
        "",
    ].join("\n");

    assert.strictEqual(gifOutput, expectedGifOutput);

    assert.strictEqual(processCalls.length, 3);
    assert.strictEqual(processCalls[1].source, gifFrame0);
    assert.strictEqual(processCalls[1].settings.contrast, 0);
    assert.strictEqual(processCalls[2].source, gifFrame1);
    assert.strictEqual(processCalls[2].settings.contrast, 77);
} finally {
    if (typeof originalDocument === "undefined") {
        delete global.document;
    } else {
        global.document = originalDocument;
    }

    if (typeof originalProcessor === "undefined") {
        delete global.Processor;
    } else {
        global.Processor = originalProcessor;
    }
}
