import { cTypeFor } from "./packing.js";
import { sanitizeVarName } from "../core/settings.js";

function indentTokens(tokens) {
    const lines = [];
    for (let i = 0; i < tokens.length; i += 16) {
        lines.push("\t" + tokens.slice(i, i + 16).join(", "));
    }
    return lines.join(",\n");
}

function arrayBlock(tokens, safe, name, progmem) {
    const type = cTypeFor(safe.pixelFormat);
    return `const ${type} ${name} []${progmem ? " PROGMEM" : ""} = {\n`
        + `${indentTokens(tokens)}\n`
        + `};`;
}

function dimsBlock(safe) {
    return `const int ${safe.varName}_width = ${safe.width};\n`
        + `const int ${safe.varName}_height = ${safe.height};`;
}

function frameComment(frame) {
    return `// '${frame.name}', ${frame.width}x${frame.height}px`;
}

export function formatPlain(frames, safe) {
    const blocks = frames.map((f) => `${frameComment(f)}\n${indentTokens(f.tokens).replace(/\t/g, "")}`);
    return blocks.join("\n\n") + "\n";
}

export function formatArduinoMulti(frames, safe) {
    const type = cTypeFor(safe.pixelFormat);
    const blocks = ["// Generated by image2cpp", dimsBlock(safe)];
    const names = [];
    const used = new Set();
    frames.forEach((f, idx) => {
        let name = frames.length > 1 ? sanitizeVarName(`${safe.varName}_${f.name}`, `${safe.varName}_${idx}`) : safe.varName;
        // Two frame names can sanitize to the same identifier; suffix on collision
        // so the emitted C array names (and the pointer table) stay unique/valid.
        if (used.has(name)) {
            let suffix = 2;
            while (used.has(`${name}_${suffix}`)) suffix++;
            name = `${name}_${suffix}`;
        }
        used.add(name);
        names.push(name);
        blocks.push(`${frameComment(f)}\n${arrayBlock(f.tokens, safe, name, true)}`);
    });
    const arrName = `${safe.varName}_array`;
    const list = names.map((n) => "\t" + n).join(",\n");
    blocks.push(
        `const int ${arrName}_len = ${names.length};\n`
        + `const ${type}* ${arrName}[${names.length}] = {\n${list}\n};`,
    );
    return blocks.join("\n\n") + "\n";
}

export function formatArduinoSingle(frames, safe) {
    const type = cTypeFor(safe.pixelFormat);
    const body = frames.map((f) => `\t${frameComment(f)}\n${indentTokens(f.tokens)}`).join(",\n");
    return `const ${type} ${safe.varName} [] PROGMEM = {\n${body}\n};\n`;
}

export function formatAdafruitGfx(frames, safe) {
    // GFX bitmap fonts are strictly 1-bit; normalizeSettings forces pixelFormat
    // to mono1 for this output, so each token is exactly one packed byte and the
    // glyph bitmapOffset below can accumulate token counts as byte offsets.
    const id = safe.varName;
    const bitmapBody = frames.map((f) => `\t${frameComment(f)}\n${indentTokens(f.tokens)}`).join(",\n");
    let out = `const unsigned char ${id}Bitmap [] PROGMEM = {\n${bitmapBody}\n};\n\n`;

    const allSingleChar = frames.length > 0 && frames.every((f) => f.name && f.name.length === 1);
    let nextChar = safe.firstAsciiChar;
    let offset = 0;

    out += `const GFXbitmapGlyph ${id}Glyphs [] PROGMEM = {\n`;
    out += frames.map((f, i) => {
        const rawChar = allSingleChar ? f.name : String.fromCharCode(nextChar++);
        const ch = rawChar.replace(/\\/g, "\\\\").replace(/'/g, "\\'"); // safe C char literal
        const line = `\t{ ${offset}, ${f.width}, ${f.height}, ${safe.xAdvance}, '${ch}' }`;
        offset += f.tokens.length; // byte offset (mono1: 1 token === 1 byte)
        return line + (i < frames.length - 1 ? "," : "") + ` // '${f.name}'`;
    }).join("\n");
    out += `\n};\n\n`;

    out += `const GFXbitmapFont ${id}Font PROGMEM = {\n`
        + `\t(uint8_t *)${id}Bitmap,\n`
        + `\t(GFXbitmapGlyph *)${id}Glyphs,\n`
        + `\t${frames.length}\n};\n`;
    return out;
}
